CREATE DATABASE ECOMMERCE;
GO

USE ECOMMERCE;
GO


CREATE TABLE USUARIO(
	COD_USUARIO 		INT 		NOT NULL IDENTITY(1,1),
	NOME		 		VARCHAR(30) NOT NULL,
	EMAIL 				VARCHAR(20)	NOT NULL,
	SENHA				VARCHAR(20) NOT NULL,
	COD_PERFIL			INT 		NOT NULL,

	CONSTRAINT PK_USUARIO_COD_USUARIO 	PRIMARY KEY (COD_USUARIO)
);
GO


CREATE TABLE PERFIL(
	COD_PERFIL			INT 		NOT NULL IDENTITY(1,1),
	PERFIL		 	VARCHAR(30) NOT NULL
	CONSTRAINT PK_PERFIL_COD_PERFIL 	PRIMARY KEY (COD_PERFIL)
);
GO

CREATE TABLE PRODUTO(
	COD_PRODUTO INT 	NOT NULL IDENTITY(1,1),
	NOME	VARCHAR(30) NOT NULL,
	PRECO DECIMAL(7,2) NOT NULL
	
	CONSTRAINT PK_PRODUTO_COD_PRODUTO PRIMARY KEY(COD_PRODUTO)
);
GO



CREATE TABLE DUVIDA(
	COD_DUVIDA INTEGER NOT NULL IDENTITY(1,1),
	NOME_USUARIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	TITULO VARCHAR(20) NOT NULL

	CONSTRAINT PK_DUVIDA_COD_DUVIDA PRIMARY KEY(COD_DUVIDA)

);
GO



CREATE TABLE PEDIDO(
	COD_PEDIDO INTEGER NOT NULL IDENTITY(1,1),
	COD_PRODUTO INTEGER NOT NULL,
	COD_USUARIO INTEGER NOT NULL,
	QUANTIDADE INTEGER NOT NULL,

	CONSTRAINT PK_PEDIDO_COD_PEDIDO PRIMARY KEY(COD_PEDIDO)

);
GO



ALTER TABLE USUARIO
    ADD CONSTRAINT FK_PERFIL_COD_PERFIL FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL(COD_PERFIL)
GO


ALTER TABLE PEDIDO
	ADD CONSTRAINT FK_USUARIO_COD_USUARIO FOREIGN KEY(COD_USUARIO) REFERENCES USUARIO(COD_USUARIO)
GO


ALTER TABLE PEDIDO
	ADD CONSTRAINT FK_PRODUTO_COD_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
GO




